// <auto-generated />
namespace DevEnv_Semester_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class requiredinSkill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiredinSkill));
        
        string IMigrationMetadata.Id
        {
            get { return "201702171103589_required-in-Skill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
